name: Treinamento

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    
    env:
      NOME_IMAGEM: testesitecontagem
      NOME_COMPLETO_IMAGEM: ${{ secrets.DOCKER_USERNAME }}/$NOME_IMAGEM

    - name: Task 1 Exemplo
      run: echo 'Task 1 Exemplo'
