name: Treinamento GH Actions - Triggers

on:
 schedule:
  - cron:  '* * * * *'
 workflow_dispatch:
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    - name: Task 1 Exemplo
      if: success()
      run: echo 'Task 1 Exemplo '
    
    - name: Task 2 Exemplo
      if: failure()
      run: echo 'Task 2 Exemplo '
      
    - name: Força o Step falhar
      run: exit 1      
    
    - name: Enviar Notificação Sucesso
      if: success()
      run: echo 'Enviar Notificação Sucesso'
    
    - name: Task 4 Exemplo
      if: failure()
      run: echo 'Enviar Notificação Erro'                  
 deploy:
   runs-on: ubuntu-latest
   needs: [build]
   steps:
    - name: Task 1 Exemplo
      if: success()
      run: echo 'Task 1 Exemplo '              
