name: Treinamento

on: 
 schedule:
  # * is a special character in YAML so you have to quote this string
  - cron:  '*/1 * * * *'
      
 workflow_dispatch:

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    - name: Task 1 Exemplo
      run: echo 'Task 1 Exemplo '
