name: Treinamento GH Actions - Triggers Push

on:
 push:
  branches: 
   - master
 pull_request:
  paths-ignore: 
   - '**/main.yml'
 workflow_dispatch:

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    - name: Task 1 Exemplo
      run: echo 'Task 1 Exemplo '
