name: Treinamento GH Actions - Triggers Push

on:
 push:
  branches: 
   - master
  paths-ignore: 
   - '**/main.yml'
 workflow_dispatch:
 schedule:
  - cron:  '* * * * *'

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    - name: Task 1 Exemplo
      run: echo 'Task 1 Exemplo '
