name: Treinamento GH Actions - Triggers

on:
 push:
  branches: 
   - master
 schedule:
  - cron:  '* * * * *'
 workflow_dispatch:
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    - name: Task 1 Exemplo
      run: echo 'Task 1 Exemplo '
    
    - name: Task 2 Exemplo
      run: echo 'Task 2 Exemplo '
      
    - name: Task 3 Exemplo
      run: echo ${{ github.ref	 }}      
         
    - name: Enviar Notificação Sucesso
      if: success()
      run: echo 'Enviar Notificação Sucesso'
    
    - name: Enviar Notificação Falha
      if: failure()
      run: echo 'Enviar Notificação Erro'                  
 deploy-dev:
   if: github.ref == 'refs/heads/developer'
   runs-on: ubuntu-latest
   needs: [build]
   steps:
    - name: Task 1 Exemplo
      if: success()
      run: echo 'Task 1 Exemplo '                    
 deploy-prod:
   if: github.ref == 'refs/heads/master'
   runs-on: ubuntu-latest
   needs: [build]
   steps:
    - name: Task 1 Exemplo
      if: success()
      run: echo 'Task 1 Exemplo '              
